// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package image_repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Image struct {
	ID         pgtype.UUID `json:"id"`
	PublicID   string      `json:"public_id"`
	Format     string      `json:"format"`
	HotelID    pgtype.UUID `json:"hotel_id"`
	UserID     pgtype.UUID `json:"user_id"`
	RoomTypeID pgtype.UUID `json:"room_type_id"`
}
