// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package hotel_repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Hotel struct {
	ID      pgtype.UUID `json:"id"`
	Name    string      `json:"name"`
	Address string      `json:"address"`
}
