// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package room_type_repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RoomType struct {
	ID      pgtype.UUID `json:"id"`
	Name    string      `json:"name"`
	Price   int32       `json:"price"`
	HotelID pgtype.UUID `json:"hotel_id"`
}
