// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: room-type.queries.sql

package room_type_repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRoomTypeById = `-- name: GetRoomTypeById :one
SELECT id, name, price, hotel_id
FROM room_types
WHERE id = $1
`

func (q *Queries) GetRoomTypeById(ctx context.Context, id pgtype.UUID) (RoomType, error) {
	row := q.db.QueryRow(ctx, getRoomTypeById, id)
	var i RoomType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.HotelID,
	)
	return i, err
}

const getRoomTypesByHotelId = `-- name: GetRoomTypesByHotelId :many
SELECT id, name, price, hotel_id
FROM room_types rt
WHERE hotel_id = $1
ORDER BY rt.name
LIMIT 10
`

func (q *Queries) GetRoomTypesByHotelId(ctx context.Context, hotelID pgtype.UUID) ([]RoomType, error) {
	rows, err := q.db.Query(ctx, getRoomTypesByHotelId, hotelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoomType
	for rows.Next() {
		var i RoomType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.HotelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
