// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package rating_repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Rating struct {
	ID      pgtype.UUID `json:"id"`
	Score   int32       `json:"score"`
	HotelID pgtype.UUID `json:"hotel_id"`
	UserID  pgtype.UUID `json:"user_id"`
	Comment pgtype.Text `json:"comment"`
}
