// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: PATH/hotel.proto

package hotels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHotelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotelRequest) Reset() {
	*x = GetHotelRequest{}
	mi := &file_PATH_hotel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotelRequest) ProtoMessage() {}

func (x *GetHotelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PATH_hotel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotelRequest.ProtoReflect.Descriptor instead.
func (*GetHotelRequest) Descriptor() ([]byte, []int) {
	return file_PATH_hotel_proto_rawDescGZIP(), []int{0}
}

func (x *GetHotelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetHotelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotelResponse) Reset() {
	*x = GetHotelResponse{}
	mi := &file_PATH_hotel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotelResponse) ProtoMessage() {}

func (x *GetHotelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PATH_hotel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotelResponse.ProtoReflect.Descriptor instead.
func (*GetHotelResponse) Descriptor() ([]byte, []int) {
	return file_PATH_hotel_proto_rawDescGZIP(), []int{1}
}

func (x *GetHotelResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetHotelResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetHotelResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_PATH_hotel_proto protoreflect.FileDescriptor

const file_PATH_hotel_proto_rawDesc = "" +
	"\n" +
	"\x10PATH/hotel.proto\x12\x05hotel\"!\n" +
	"\x0fGetHotelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"P\n" +
	"\x10GetHotelResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress2K\n" +
	"\fHotelService\x12;\n" +
	"\bGetHotel\x12\x16.hotel.GetHotelRequest\x1a\x17.hotel.GetHotelResponseB\n" +
	"Z\b.;hotelsb\x06proto3"

var (
	file_PATH_hotel_proto_rawDescOnce sync.Once
	file_PATH_hotel_proto_rawDescData []byte
)

func file_PATH_hotel_proto_rawDescGZIP() []byte {
	file_PATH_hotel_proto_rawDescOnce.Do(func() {
		file_PATH_hotel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PATH_hotel_proto_rawDesc), len(file_PATH_hotel_proto_rawDesc)))
	})
	return file_PATH_hotel_proto_rawDescData
}

var file_PATH_hotel_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_PATH_hotel_proto_goTypes = []any{
	(*GetHotelRequest)(nil),  // 0: hotel.GetHotelRequest
	(*GetHotelResponse)(nil), // 1: hotel.GetHotelResponse
}
var file_PATH_hotel_proto_depIdxs = []int32{
	0, // 0: hotel.HotelService.GetHotel:input_type -> hotel.GetHotelRequest
	1, // 1: hotel.HotelService.GetHotel:output_type -> hotel.GetHotelResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PATH_hotel_proto_init() }
func file_PATH_hotel_proto_init() {
	if File_PATH_hotel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PATH_hotel_proto_rawDesc), len(file_PATH_hotel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_PATH_hotel_proto_goTypes,
		DependencyIndexes: file_PATH_hotel_proto_depIdxs,
		MessageInfos:      file_PATH_hotel_proto_msgTypes,
	}.Build()
	File_PATH_hotel_proto = out.File
	file_PATH_hotel_proto_goTypes = nil
	file_PATH_hotel_proto_depIdxs = nil
}
