// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: PATH/hotel.proto

package hotel_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHotelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotelRequest) Reset() {
	*x = GetHotelRequest{}
	mi := &file_PATH_hotel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotelRequest) ProtoMessage() {}

func (x *GetHotelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PATH_hotel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotelRequest.ProtoReflect.Descriptor instead.
func (*GetHotelRequest) Descriptor() ([]byte, []int) {
	return file_PATH_hotel_proto_rawDescGZIP(), []int{0}
}

func (x *GetHotelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetHotelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotelResponse) Reset() {
	*x = GetHotelResponse{}
	mi := &file_PATH_hotel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotelResponse) ProtoMessage() {}

func (x *GetHotelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PATH_hotel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotelResponse.ProtoReflect.Descriptor instead.
func (*GetHotelResponse) Descriptor() ([]byte, []int) {
	return file_PATH_hotel_proto_rawDescGZIP(), []int{1}
}

func (x *GetHotelResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetHotelResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateHotelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHotelRequest) Reset() {
	*x = CreateHotelRequest{}
	mi := &file_PATH_hotel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHotelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHotelRequest) ProtoMessage() {}

func (x *CreateHotelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PATH_hotel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHotelRequest.ProtoReflect.Descriptor instead.
func (*CreateHotelRequest) Descriptor() ([]byte, []int) {
	return file_PATH_hotel_proto_rawDescGZIP(), []int{2}
}

func (x *CreateHotelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateHotelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHotelResponse) Reset() {
	*x = CreateHotelResponse{}
	mi := &file_PATH_hotel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHotelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHotelResponse) ProtoMessage() {}

func (x *CreateHotelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PATH_hotel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHotelResponse.ProtoReflect.Descriptor instead.
func (*CreateHotelResponse) Descriptor() ([]byte, []int) {
	return file_PATH_hotel_proto_rawDescGZIP(), []int{3}
}

type GetAllHotelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllHotelsRequest) Reset() {
	*x = GetAllHotelsRequest{}
	mi := &file_PATH_hotel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllHotelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllHotelsRequest) ProtoMessage() {}

func (x *GetAllHotelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PATH_hotel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllHotelsRequest.ProtoReflect.Descriptor instead.
func (*GetAllHotelsRequest) Descriptor() ([]byte, []int) {
	return file_PATH_hotel_proto_rawDescGZIP(), []int{4}
}

type GetAllHotelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hotels        []*Hotel               `protobuf:"bytes,1,rep,name=hotels,proto3" json:"hotels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllHotelsResponse) Reset() {
	*x = GetAllHotelsResponse{}
	mi := &file_PATH_hotel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllHotelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllHotelsResponse) ProtoMessage() {}

func (x *GetAllHotelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PATH_hotel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllHotelsResponse.ProtoReflect.Descriptor instead.
func (*GetAllHotelsResponse) Descriptor() ([]byte, []int) {
	return file_PATH_hotel_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllHotelsResponse) GetHotels() []*Hotel {
	if x != nil {
		return x.Hotels
	}
	return nil
}

type Hotel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hotel) Reset() {
	*x = Hotel{}
	mi := &file_PATH_hotel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hotel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hotel) ProtoMessage() {}

func (x *Hotel) ProtoReflect() protoreflect.Message {
	mi := &file_PATH_hotel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hotel.ProtoReflect.Descriptor instead.
func (*Hotel) Descriptor() ([]byte, []int) {
	return file_PATH_hotel_proto_rawDescGZIP(), []int{6}
}

func (x *Hotel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Hotel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_PATH_hotel_proto protoreflect.FileDescriptor

const file_PATH_hotel_proto_rawDesc = "" +
	"\n" +
	"\x10PATH/hotel.proto\"!\n" +
	"\x0fGetHotelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"6\n" +
	"\x10GetHotelResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"(\n" +
	"\x12CreateHotelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x15\n" +
	"\x13CreateHotelResponse\"\x15\n" +
	"\x13GetAllHotelsRequest\"6\n" +
	"\x14GetAllHotelsResponse\x12\x1e\n" +
	"\x06hotels\x18\x01 \x03(\v2\x06.HotelR\x06hotels\"+\n" +
	"\x05Hotel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\xb6\x01\n" +
	"\fHotelService\x12/\n" +
	"\bGetHotel\x12\x10.GetHotelRequest\x1a\x11.GetHotelResponse\x128\n" +
	"\vCreateHotel\x12\x13.CreateHotelRequest\x1a\x14.CreateHotelResponse\x12;\n" +
	"\fGetAllHotels\x12\x14.GetAllHotelsRequest\x1a\x15.GetAllHotelsResponseB\fZ\n" +
	".;hotel_pbb\x06proto3"

var (
	file_PATH_hotel_proto_rawDescOnce sync.Once
	file_PATH_hotel_proto_rawDescData []byte
)

func file_PATH_hotel_proto_rawDescGZIP() []byte {
	file_PATH_hotel_proto_rawDescOnce.Do(func() {
		file_PATH_hotel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PATH_hotel_proto_rawDesc), len(file_PATH_hotel_proto_rawDesc)))
	})
	return file_PATH_hotel_proto_rawDescData
}

var file_PATH_hotel_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_PATH_hotel_proto_goTypes = []any{
	(*GetHotelRequest)(nil),      // 0: GetHotelRequest
	(*GetHotelResponse)(nil),     // 1: GetHotelResponse
	(*CreateHotelRequest)(nil),   // 2: CreateHotelRequest
	(*CreateHotelResponse)(nil),  // 3: CreateHotelResponse
	(*GetAllHotelsRequest)(nil),  // 4: GetAllHotelsRequest
	(*GetAllHotelsResponse)(nil), // 5: GetAllHotelsResponse
	(*Hotel)(nil),                // 6: Hotel
}
var file_PATH_hotel_proto_depIdxs = []int32{
	6, // 0: GetAllHotelsResponse.hotels:type_name -> Hotel
	0, // 1: HotelService.GetHotel:input_type -> GetHotelRequest
	2, // 2: HotelService.CreateHotel:input_type -> CreateHotelRequest
	4, // 3: HotelService.GetAllHotels:input_type -> GetAllHotelsRequest
	1, // 4: HotelService.GetHotel:output_type -> GetHotelResponse
	3, // 5: HotelService.CreateHotel:output_type -> CreateHotelResponse
	5, // 6: HotelService.GetAllHotels:output_type -> GetAllHotelsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_PATH_hotel_proto_init() }
func file_PATH_hotel_proto_init() {
	if File_PATH_hotel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PATH_hotel_proto_rawDesc), len(file_PATH_hotel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_PATH_hotel_proto_goTypes,
		DependencyIndexes: file_PATH_hotel_proto_depIdxs,
		MessageInfos:      file_PATH_hotel_proto_msgTypes,
	}.Build()
	File_PATH_hotel_proto = out.File
	file_PATH_hotel_proto_goTypes = nil
	file_PATH_hotel_proto_depIdxs = nil
}
